# files or folders that need to be backed up. multiple files are supported.
backup-files:
  - /Users/Yunis/Desktop/test

# compress mode. supported zip, tar.gz. default is tar.gz.
compress-mode: tar.gz
# archive prefix. default is Archive, the backup files will be packaged in Archive-yyyy-MM-dd_HH::mm:ss.zip(tar.gz)
archive-prefix: Archive
# cron expression triggered by backup job. default is 0 0 0 * * *. detail see https://github.com/zslayton/cron
job-cron: 0 0 0 * * *

# backup target, default is backup-server. supporting qiniu, aliyun oss, tencent oss
backup-target:
  - backer-server

backer-server:
  ip: 127.0.0.1
  port: 9618

qiniu:
  access-key:
  secret-key:
  bucket-name:

# todo
aliyun-oss:

# todo
tencent-oss: